repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff-format
        args: []
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]